services:
  app:
    container_name: alangeorge-dev
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8282:8282"
      - "42069:42069"
    env_file:
      - .env
    restart: unless-stopped
